
CREATE MATERIALIZED VIEW U_DW_AUCTIONS.BOARD_AUCTIONS
PARALLEL 4
BUILD IMMEDIATE 
REFRESH COMPLETE
ON DEMAND
 NEXT  sysdate + 1 
AS
SELECT 
        TAF.ID_AUCTION ,
        
        DPS.ID_PROD , 
        DPS.NAME DPS_NAME, 
        DPS.START_OF_COSTS    DPS_START_OF_COSTS, 
        DPS.FINISH_OF_COST    DPS_FINISH_OF_COST, 
        DPS.CATEGORY          DPS_CATEGORY, 
        DPS.IMAGE             DPS_IMAGE, 
        DPS.PLATFORM          DPS_PLATFORM, 
        DPS.CATEGORY_PLATFORM DPS_CATEGORY_PLATFORM , 
        DPS.IMAGE_PLATFORM    DPS_IMAGE_PLATFORM, 
        DPS.START_DTM_UPD     DPS_START_DTM_UPD, 
        DPS.END_DTM_UPD       DPS_END_DTM_UPD,
       
        TAF.START_DTM             AUCT_START_DTM      ,
        TAF.FINISH_DTM            AUCT_FINISH_DTM       ,
        TAF.DURATION              AUCT_DURATION       ,
        TAF.START_COST            AUCT_START_COST       ,
        TAF.COST                  AUCT_COST,

        DSS.ID_SELLERS , 
        DSS.F_NAME DSS_F_NAME, 
        DSS.S_NAME DSS_S_NAME, 
        DSS.PHONE DSS_PHONE, 
        DSS.EMAIL DSS_EMAIL, 
        DSS.COUNTRY_ID DSS_COUNTRY_ID, 
        DSS.CITY DSS_CITY, 
        DSS.STREET DSS_STREET, 
        DSS.IMAGE DSS_IMAGE, 
        DSS.DATE_REG DSS_DATE_REG, 
        DSS.START_DTM_UPD DSS_START_DTM_UPD, 
        DSS.END_DTM_UPD  DSS_END_DTM_UPD ,
        
        DBS.ID_BUYERS , 
        DBS.F_NAME DBS_F_NAME, 
        DBS.S_NAME DBS_S_NAME, 
        DBS.PHONE DBS_PHONE, 
        DBS.EMAIL DBS_EMAIL, 
        DBS.COUNTRY_ID DBS_COUNTRY_ID, 
        DBS.CITY DBS_CITY, 
        DBS.STREET DBS_STREET, 
        DBS.IMAGE DBS_IMAGE, 
        DBS.DATE_REG DBS_DATE_REG, 
        DBS.START_DTM_UPD DBS_START_DTM_UPD, 
        DBS.END_DTM_UPD  DBS_END_DTM_UPD ,
        
        TAF.DESCRIPTION  AUCT_DESCRIPTION        ,
        TAF.COMPLETE     AUCT_COMPLETE        ,
        TAF.LOAD_DTM  AUCT_LOAD_DTM           
FROM 
    U_DW_AUCTIONS.FCT_T_AUCTIONS_F TAF
    
    LEFT JOIN 
    U_DW_PRODUCTS.DIM_PRODUCTS_SAL DPS
        ON  
        TAF.ID_PROD = DPS.ID_PROD
    
    LEFT JOIN 
    U_DW_PERSONS.DIM_BUYERS_SAL DBS
        ON  
        TAF.BUYER = DBS.ID_BUYERS
    
    LEFT JOIN 
    U_DW_PERSONS.DIM_SELLERS_SAL DSS
        ON  
        TAF.SELLER = DSS.ID_SELLERS ;
        