--SELECT * FROM EXT_FILES;
--
--FILE_NAME                      |FILE_CONTENT|
---------------------------------+------------+
--iso_3166_2.tab                 |[BLOB]      |
--iso-639-3-Macro.tab            |[BLOB]      |
--iso-639-3.tab                  |[BLOB]      |
--iso_3166.tab                   |[BLOB]      |
--iso_3166_geo_un.tab            |[BLOB]      |
--iso_3166_geo_un_contries.tab   |[BLOB]      |
--iso_3166_groups_un.tab         |[BLOB]      |
--iso_3166_groups_un_contries.tab|[BLOB]      |

CREATE TABLE tmp (
    ID_T NUMBER GENERATED BY DEFAULT AS IDENTITY, 
    FILE_NAME VARCHAR2(1000  BYTE), 
    FILE_CONTENT BLOB,
    PRIMARY KEY (ID_T)
);


declare
num_value NUMBER ;
BEGIN
     FOR i IN 1..80000 LOOP
        num_value   := DBMS_Random.Value(1,8);
        insert into tmp (FILE_NAME, FILE_CONTENT) SELECT  * FROM ext_files where ROWNUM < (num_value+1) OFFSET (num_value-1) ROWS;
        commit;
    END LOOP;
END;
