
WITH TMP_T
AS
(
select TSS.NAME SUBSCRIPTION,
    trunc(tsuf.START_DTM, 'YYYY')      AS YEAR,
    TO_CHAR(tsuf.START_DTM, 'MM')      AS MONTH,
    'MONTH' ASD,
    SUM(tsuf.PAYMENT) AS PROFIT_BY_MOUNTH

    from U_DW_SUBSTRICTIONS.T_SUBSCRIPTIONS_USER_F tsuf
    inner join
    (SELECT *
    FROM
    U_DW_SUBSTRICTIONS.T_SUBSCRIPTIONS TS
    INNER JOIN
    U_DW_SUBSTRICTIONS.T_SUBSCRIPTIONS_NAME TSN
    ON
    TS.ID_SUBSCRIPTIONS_NAME=TSN.ID_SUBSCRIPTIONS_NAME)
    TSS
    on
    tsuf.ID_SUBSCRIPTIONS=TSS.ID_SUBSCRIPTIONS
    GROUP BY
        TSS.NAME,
        trunc(tsuf.START_DTM, 'YYYY'),
         TO_CHAR(tsuf.START_DTM, 'MM')
    ORDER BY
    SUBSCRIPTION,
    YEAR,
    MONTH
)

SELECT
    SUBSCRIPTION,
    YEAR,
    MONTH,
    ASD,
    PROFIT_BY_MOUNTH
FROM
TMP_T
 MODEL
    PARTITION BY (SUBSCRIPTION)
    DIMENSION BY (YEAR, MONTH, ASD)
    MEASURES (PROFIT_BY_MOUNTH)
    RULES (
        PROFIT_BY_MOUNTH[FOR YEAR IN (SELECT DISTINCT YEAR FROM TMP_T), NULL, 'YEAR'] = SUM(PROFIT_BY_MOUNTH)[CV(YEAR), ANY, 'MONTH'],
        PROFIT_BY_MOUNTH[NULL, NULL, 'ALL'] = SUM(PROFIT_BY_MOUNTH)[ANY, NULL, 'YEAR']
    )
ORDER BY
    SUBSCRIPTION,
    YEAR,
    MONTH
    ;