EXPLAIN PLAN FOR
SELECT DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
    FROM EMP 
        RIGHT JOIN DEPT
        ON EMP.DEPTNO = DEPT.DEPTNO
        WHERE  EMP.DEPTNO IS NULL;

SELECT * FROM TABLE (DBMS_XPLAN.DISPLAY);
